//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNShare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertise_Product_Detail
    {
        public int Package_Detail_ID { get; set; }
        public int Package_ID { get; set; }
        public decimal Unit_Price { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Begin_Time { get; set; }
        public System.DateTime End_Time { get; set; }
        public System.DateTime Order_Time { get; set; }
        public Nullable<int> Product_ID { get; set; }
    
        public virtual Advertise_Product Advertise_Product { get; set; }
        public virtual Product Product { get; set; }
    }
}
