//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNShare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Comment_ID { get; set; }
        public int Product_ID { get; set; }
        public int Member_ID { get; set; }
        public string Review { get; set; }
        public Nullable<double> Rank { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Customer_Infomation Customer_Infomation { get; set; }
        public virtual Product Product { get; set; }
    }
}
