//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNShare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Infomation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer_Infomation()
        {
            this.Comments = new HashSet<Comment>();
            this.Customer_Infomation1 = new HashSet<Customer_Infomation>();
            this.Interests = new HashSet<Interest>();
            this.MemberAchievements = new HashSet<MemberAchievement>();
            this.Orders = new HashSet<Order>();
            this.Order_Detail = new HashSet<Order_Detail>();
            this.PocketLists = new HashSet<PocketList>();
            this.Surveys = new HashSet<Survey>();
        }
    
        public int Member_ID { get; set; }
        public string Resident_ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Phone_Number { get; set; }
        public string Email { get; set; }
        public Nullable<int> Disctrict_ID { get; set; }
        public string Address { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public string Nickname { get; set; }
        public string Password { get; set; }
        public bool IsAllergy_ { get; set; }
        public string AllergyDescription { get; set; }
        public string Note { get; set; }
        public int Status_ID { get; set; }
        public byte[] Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Infomation> Customer_Infomation1 { get; set; }
        public virtual Customer_Infomation Customer_Infomation2 { get; set; }
        public virtual District District { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interest> Interests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberAchievement> MemberAchievements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PocketList> PocketLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Survey> Surveys { get; set; }
    }
}
