//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNShare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_Detail()
        {
            this.Surveys = new HashSet<Survey>();
        }
    
        public int Order_Detail_ID { get; set; }
        public int Order_ID { get; set; }
        public int Product_Detail_ID { get; set; }
        public int Member_ID { get; set; }
        public int Status_ID { get; set; }
        public Nullable<int> Grade { get; set; }
    
        public virtual Customer_Infomation Customer_Infomation { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product_Detail Product_Detail { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Survey> Surveys { get; set; }
    }
}
