//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNShare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.AchievementLists = new HashSet<AchievementList>();
            this.Advertise_Product_Detail = new HashSet<Advertise_Product_Detail>();
            this.Comments = new HashSet<Comment>();
            this.Image_List = new HashSet<Image_List>();
            this.PocketLists = new HashSet<PocketList>();
            this.PocketLists1 = new HashSet<PocketList>();
            this.Product_Detail = new HashSet<Product_Detail>();
            this.Product1 = new HashSet<Product>();
            this.ProductCategories = new HashSet<ProductCategory>();
        }
    
        public int Product_ID { get; set; }
        public Nullable<int> Class_ID { get; set; }
        public string Product_Name { get; set; }
        public string Product_Intro { get; set; }
        public int Supplier_ID { get; set; }
        public Nullable<int> Age_ID { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<System.DateTime> ReleasedTime { get; set; }
        public Nullable<int> Times { get; set; }
        public string Interval { get; set; }
        public string Note { get; set; }
        public int Status_ID { get; set; }
        public bool IsClass_ { get; set; }
        public Nullable<double> Commision { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AchievementList> AchievementLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advertise_Product_Detail> Advertise_Product_Detail { get; set; }
        public virtual Age Age { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image_List> Image_List { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PocketList> PocketLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PocketList> PocketLists1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Detail> Product_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product1 { get; set; }
        public virtual Product Product2 { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCategory> ProductCategories { get; set; }
    }
}
